name: 'Generate technical debt issue'
description: 'Parse pull request body/comment and automatically generate GitHub issues for technical debt'
branding:
  icon: 'bar-chart'
  color: 'blue'
inputs:
  title_prefix:
    description: 'Allows you to change the prefix used for debt issues'
    required: false
    default: '[DEBT]'
  title_start:
    description: 'Allows you to change the regex used for debt issues'
    required: false
    default: '<!--\[DEBT_ISSUE_TITLE\]-->'
  title_end:
    description: 'Allows you to define the title endpoint'
    required: false
    default: 'line'
  title_end_regex:
    description: 'Allows you to change the regex used for title ending'
    required: false
    default: '<!--\[DEBT_TITLE_END\]-->'
  body_start:
    description: 'Allows you to change the regex used for debt issues'
    required: false
    default: '<!--\[DEBT_BODY_START\]-->'
  body_end:
    description: 'Allows you to define the body endpoint'
    required: false
    default: 'paragraph'
  body_end_regex:
    description: 'Allows you to change the regex used for body ending'
    required: false
    default: '<!--\[DEBT_BODY_END\]-->'
  token:
    description: 'The GitHub auth token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
